<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hibegin</groupId>
        <artifactId>zrlog-base</artifactId>
        <version>3.5.11-SNAPSHOT</version>
    </parent>

    <artifactId>zrlog-template</artifactId>
    <version>3.5.11-SNAPSHOT</version>
    <name>ZrLog Template</name>

    <dependencies>
        <dependency>
            <groupId>com.hibegin</groupId>
            <artifactId>zrlog-service</artifactId>
        </dependency>
    </dependencies>

</project>
